// extension.js/examples/svelte/src/sidebar/SidebarApp.svelte
<script lang="ts">
import logo from '../images/icon.png'
</script>

<div class="sidebar_app">
  <img class="sidebar_logo" src={logo} alt="The Svelte logo" />
  <h1 class="sidebar_title">Sidebar Panel</h1>
  <p class="sidebar_description">
    Learn more in the{' '}
    <a
      href="https://extension.js.org"
      target="_blank"
      rel="noopener noreferrer"
    >Extension.js docs</a>
    .
  </p>
</div>

// extension.js/examples/react/src/sidebar/SidebarApp.tsx
import './styles.css'
import reactLogo from '../images/icon.png'

export default function SidebarApp() {
  return (
    <div className="sidebar_app">
      <header>
        <img
          className="sidebar_logo"
          src={reactLogo}
          alt="The React logo"
          width="120"
        />
        <h1 className="sidebar_title">Sidebar Panel</h1>
        <p className="sidebar_description">
          Learn more in the{' '}
          <a
            href="https://extension.js.org"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:text-blue-500 dark:text-blue-400 dark:hover:text-blue-300 transition-colors duration-200"
          >
            Extension.js docs
          </a>
          .
        </p>
      </header>
    </div>
  )
}
