// extension.js/examples/new-vue/src/newtab/NewTabApp.vue
<script lang="ts" setup>
import iconUrl from '../images/icon.png'

const message = 'Welcome to your Vue Extension.'
</script>
<template>
  <header>
    <h1>
      <img
        class="vue"
        :src="iconUrl"
        alt="The Vue logo"
        width="120px"
      />
      <br />
      {{message}}
    </h1>
    <p>
      Learn more in the 
      <a href="https://extension.js.org" target="_blank" rel="noopener noreferrer">Extension.js docs</a>
      .
    </p>
  </header>
</template>

// extension.js/examples/new-preact/src/newtab/NewTabApp.tsx
import './styles.css'
import preactLogo from '../images/icon.png'

export default function ContentApp() {
  return (
    <header>
      <h1>
        <img
          className="preact"
          src={preactLogo}
          alt="The Preact logo"
          width="120px"
        />
        <br />
        Welcome to your Preact Extension.
      </h1>
      <p>
        Learn more in the{' '}
        <a
          href="https://extension.js.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Extension.js docs
        </a>
        .
      </p>
    </header>
  )
}
