// extension.js/examples/svelte/src/content/ContentApp.svelte
<script>
import logo from '../images/icon.png'

function openSidebar() {
  if (import.meta.env.EXTENSION_PUBLIC_BROWSER === 'firefox') {
    browser.runtime.sendMessage({type: 'openSidebar'})
  } else {
    chrome.runtime.sendMessage({type: 'openSidebar'})
  }
}
</script>

<button
  type="button"
  class="content_pill"
  aria-label="Open sidebar"
  on:click={openSidebar}
>
  <img class="content_pill_logo" src={logo} alt="" aria-hidden="true" />
  <span class="content_pill_text">Open sidebar</span>
  </button>

// extension.js/examples/react/src/content/ContentApp.tsx
import logo from '../images/icon.png'

export default function ContentApp() {
  const handleClick = () => {
    if (import.meta.env.EXTENSION_PUBLIC_BROWSER === 'firefox') {
      browser.runtime.sendMessage({type: 'openSidebar'})
    } else {
      chrome.runtime.sendMessage({type: 'openSidebar'})
    }
  }

  return (
    <button
      type="button"
      className="content_pill"
      onClick={handleClick}
      aria-label="Open sidebar"
    >
      <img className="content_pill_logo" src={logo} alt="" aria-hidden="true" />
      <span className="content_pill_text">Open sidebar</span>
    </button>
  )
}
